NOISSUE - Fix cvm connections issues (#11)
* Fix cvm connections issues

Signed-off-by: Jilks Smith <smithjilks@gmail.com>

* Update config files

Signed-off-by: Jilks Smith <smithjilks@gmail.com>

* Update am-certs-config.yaml

Signed-off-by: Jilks Smith <smithjilks@gmail.com>

* Add auto create initial scripts

Signed-off-by: Jilks Smith <smithjilks@gmail.com>

* Updates backends service ports to use values from values.yaml

Signed-off-by: Jilks Smith <smithjilks@gmail.com>

* Remove unnecessary IPs from certs config

Signed-off-by: Jilks Smith <smithjilks@gmail.com>

* Revert argocd file

Signed-off-by: Jilks Smith <smithjilks@gmail.com>

---------

Signed-off-by: Jilks Smith <smithjilks@gmail.com>

diff --git a/charts/prism/templates/backends-deployment.yaml b/charts/prism/templates/backends-deployment.yaml
--- a/charts/prism/templates/backends-deployment.yaml
+++ b/charts/prism/templates/backends-deployment.yaml
@@ -58,14 +58,13 @@ spec:
           ports:
             - containerPort: {{ .Values.backends.httpPort }}
               protocol: TCP
-            - containerPort: 7006
+            - containerPort: {{ .Values.backends.grpcPort }}
               protocol: TCP
-            - containerPort: 7011
+            - containerPort: {{ .Values.backends.cvmsPort }}
               protocol: TCP
           volumeMounts:
             - name: {{ .Release.Name }}-backends-secrets
               mountPath: /etc/secret
-              readOnly: true
 
             - name: {{ .Release.Name }}-backends-providers-config
               mountPath: /providers/azure.toml
@@ -96,6 +95,9 @@ spec:
               mountPath: /providers/cloud-init/config.yml
               subPath: cloud_init.yml
 
+            - name: {{ .Release.Name }}-backends-certs-volume
+              mountPath: /etc/certs
+
           resources:
             requests:
               cpu: "125m"
@@ -104,11 +106,57 @@ spec:
               cpu: "350m"
               memory: "512Mi"
 
+      initContainers:
+        - name: init-certs
+          image: alpine:latest
+          command: [ "/bin/sh", "-c" ]
+          args:
+            - |
+              # Install Git
+              apk update && apk add --no-cache curl bash jq git go make netcat-openbsd
+
+              until nc -z {{ .Release.Name }}-{{ .Values.amCerts.host }} 9010; do
+                echo "Waiting for Prism AM Certs to be ready...";
+                sleep 2;
+              done
+              echo "Prism AM Certs is up. Running cert script...";
+              cp /scripts/provision_certs.sh /tmp/provision_certs.sh
+              # Check if the file was copied correctly
+              if [ -f /tmp/provision_certs.sh ]; then
+                echo "Script copied successfully to /tmp."
+                chmod +x /tmp/provision_certs.sh
+              else
+                echo "Failed to copy the script to /tmp."
+                exit 1
+              fi
+              echo "Running script"
+              /tmp/provision_certs.sh
+
+          env:
+            - name: SECRET_NAME
+              value: "{{ .Release.Name }}-backends-secrets"
+            - name: SECRET_NAMESPACE
+              value: "{{ .Release.Namespace }}"
+            - name: AM_CERTS_SERVICE_HOST
+              value: "{{ .Release.Name }}-{{ .Values.amCerts.host }}"
+            - name: AM_CERTS_SERVICE_PORT
+              value: "{{ .Values.amCerts.httpPort }}"
+          volumeMounts:
+            - name: {{ .Release.Name }}-backends-certs-volume
+              mountPath: /etc/certs
+            - name: {{ .Release.Name }}-cvms-cert-init-script
+              mountPath: /scripts
+              readOnly: false
+
       volumes:
         - name: {{ .Release.Name }}-backends-secrets
           secret:
             secretName: {{ .Release.Name }}-backends-secrets
-
         - name: {{ .Release.Name }}-backends-providers-config
           configMap:
             name: {{ .Release.Name }}-backends-providers-config-files
+        - name: {{ .Release.Name }}-cvms-cert-init-script
+          configMap:
+            name: {{ .Release.Name }}-backends-cvms-cert-init-script
+        - name: {{ .Release.Name }}-backends-certs-volume
+          emptyDir: {}
